FROM node:16-alpine

WORKDIR /app

RUN apk add  --no-cache ffmpeg

ENV NODE_ENV=production

EXPOSE 3000

COPY ./package.json ./package-lock.json ./

RUN npm ci

COPY ./public ./public

COPY ./configuration ./configuration

COPY ./dist .

COPY ./src/presentation/web/views ./presentation/web/views

CMD ["node", "/app/presentation/web/main.js"]
